AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/migrate/*"
    - "db/*/"
    - "tmp/*/"
    - "vendor/*/"
    - "bin/*/"
    - "log/*/"
    - "node_modules/**/*"
Style/Documentation:
  Enabled: false
